# Generated by Django 5.2 on 2025-05-14 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждено'), ('declined', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('registration', 'Регистрация'), ('closed', 'Закрыт')], default='registration', max_length=20),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tours', to=settings.AUTH_USER_MODEL),
        ),
    ]
