# Generated by Django 5.2 on 2025-05-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tour_max_participants_alter_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='max_participants',
            field=models.PositiveIntegerField(default=10, help_text='Максимальное количество участников'),
        ),
    ]
